### ISSUE TITLE
Delete redundant events

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-map#3]
There aren't many but here is one example of doubling: 
![screenshot 2017-04-05 12 14 33](https://cloud.githubusercontent.com/assets/25624431/24729377/9e5bbc66-19f9-11e7-9b82-120b16d1cc52.png)

**Comment by jasontev** [comment]
@aaghevli looks like there's some duplicates in the api.  Is there any duplicate validation?
