### ISSUE TITLE
Customizable ETL

### ISSUE THREAD

**Issue by jasontev** [ResistanceCalendar/resistance-calendar-map#6]
<img width="770" alt="screen shot 2017-04-05 at 6 34 19 pm" src="https://cloud.githubusercontent.com/assets/8690295/24733775/862cda1e-1a2e-11e7-84a0-020e11e3f9c4.png">

- [x] basic url customization
- [x] extra validation
- [x] support more sources (events-etl, etc.)
- [x] wizard 🔮

**Comment by InciteDemocracy** [comment]
if that 91% is right, Thats awesome!
