### ISSUE TITLE
Add Logo

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-map#8]
![screenshot 2017-04-06 08 16 51](https://cloud.githubusercontent.com/assets/25624431/24769244/80621112-1aa1-11e7-84d1-f357c57b6a75.png)

**Comment by jasontev** [comment]
closed in https://github.com/ResistanceCalendar/resistance-calendar-map/commit/bc4ee09e823dba96a7f28defc4098f0337ff37a0
